New log file opened at Tue Nov 03 02:16:50 EST 2015 by 10920@Mfts
Taking next connection to: 53414
New client attempting to connect on port: 53415-53414
  Address = /192.168.1.7:53414
This client on port 53415 has uuid 19c03131-a2e0-49ae-92c4-3c2533db6e06 configName activator humanReadableName Activator protocolVersion 3 featureTags Vector()
Connected Clients: activator-19c03131-a2e0-49ae-92c4-3c2533db6e06
Taking next connection to: 53414
New client attempting to connect on port: 53416-53414
  Address = /192.168.1.7:53414
Handshake exception on socket: 53416
sbt.impl.ipc.HandshakeException: Unable to perform handshake
	at sbt.impl.ipc.Peer.handshake(IPC.scala:46)
	at sbt.impl.ipc.MultiClientServer.<init>(IPC.scala:150)
	at sbt.server.SbtServerSocketHandler$$anon$1.run(SbtServerSocketHandler.scala:43)
Caused by: java.net.SocketException: Software caused connection abort: recv failed
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(Unknown Source)
	at java.net.SocketInputStream.read(Unknown Source)
	at java.net.SocketInputStream.read(Unknown Source)
	at java.io.BufferedInputStream.fill(Unknown Source)
	at java.io.BufferedInputStream.read(Unknown Source)
	at java.io.DataInputStream.readInt(Unknown Source)
	at sbt.impl.ipc.Peer.receive(IPC.scala:95)
	at sbt.impl.ipc.Peer.handshake(IPC.scala:49)
	... 2 more
Taking next connection to: 53414
New client attempting to connect on port: 53417-53414
  Address = /192.168.1.7:53414
This client on port 53417 has uuid d414232d-f487-4817-ac3a-9dc8c45bf774 configName activator humanReadableName Activator protocolVersion 3 featureTags Vector()
Connected Clients: activator-19c03131-a2e0-49ae-92c4-3c2533db6e06, activator-d414232d-f487-4817-ac3a-9dc8c45bf774
Taking next connection to: 53414
New client attempting to connect on port: 53424-53414
  Address = /192.168.1.7:53414
Handshake exception on socket: 53424
sbt.impl.ipc.HandshakeException: Unable to perform handshake
	at sbt.impl.ipc.Peer.handshake(IPC.scala:46)
	at sbt.impl.ipc.MultiClientServer.<init>(IPC.scala:150)
	at sbt.server.SbtServerSocketHandler$$anon$1.run(SbtServerSocketHandler.scala:43)
Caused by: java.net.SocketException: Software caused connection abort: recv failed
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(Unknown Source)
	at java.net.SocketInputStream.read(Unknown Source)
	at java.net.SocketInputStream.read(Unknown Source)
	at java.io.BufferedInputStream.fill(Unknown Source)
	at java.io.BufferedInputStream.read(Unknown Source)
	at java.io.DataInputStream.readInt(Unknown Source)
	at sbt.impl.ipc.Peer.receive(IPC.scala:95)
	at sbt.impl.ipc.Peer.handshake(IPC.scala:49)
	... 2 more
Taking next connection to: 53414
New client attempting to connect on port: 53425-53414
  Address = /192.168.1.7:53414
This client on port 53425 has uuid bc2828eb-c39e-4a41-877a-5c5cd9c1d90d configName play-fork-run humanReadableName Play Fork Run protocolVersion 1 featureTags Vector()
Connected Clients: activator-d414232d-f487-4817-ac3a-9dc8c45bf774, play-fork-run-bc2828eb-c39e-4a41-877a-5c5cd9c1d90d
Taking next connection to: 53414
